### PR TITLE
Update Porting-Buffer.md

### PR DESCRIPTION
**Pull request by Trott**
Minor updates.

### CODE REVIEW

**Comment by ChALkeR** [comment]
@Trott Thanks! Will take a look at this in about an hour.

Not sure what's wrong with «[behaviour](https://en.oxforddictionaries.com/definition/behaviour)», though.

**Review by ChALkeR — APPROVED** [review]
LGTM.

**Comment by Trott** [comment]
> Not sure what's wrong with «behaviour», though.

I was editing this with an eye towards inclusion in the Node.js repo and the style guide there is to use US English spellings. So it's not a correction exactly, and feel free to decline that particular change if you wish.

**Comment by ChALkeR** [comment]
@Trott I already merged that, thanks ;-).
I think that both of those are fine here.

**Pull request merged**
